USE DB_BEAUTY_SALON;

/*CREATE TABLE SPECIALITY(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NAME_SPECIALITY NVARCHAR(50) NOT NULL,
);

INSERT INTO SPECIALITY(NAME_SPECIALITY)
VALUES('Парикмахер');

INSERT INTO SPECIALITY(NAME_SPECIALITY)
VALUES('Визажист');

CREATE TABLE EMPLOYES(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FIRSTNAME NVARCHAR(30) NOT NULL,
	LASTNAME NVARCHAR(30) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	TEL NVARCHAR(14) NOT NULL,
	ID_SPECIALITY INT REFERENCES SPECIALITY (ID)
);

CREATE TABLE CLIENTS(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FIRSTNAME NVARCHAR(30) NOT NULL,
	LASTNAME NVARCHAR(30) NOT NULL,
	EMAIL NVARCHAR(50),
	TEL NVARCHAR(14) NOT NULL
);

CREATE TABLE FREE_DATETIME(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DATE_RECORD DATE NOT NULL,
	TIME_RECORD TIME NOT NULL,
	FREE BIT NOT NULL,
	ID_EMPLOYEE INT REFERENCES EMPLOYES (ID)
);

CREATE TABLE RECORDS(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ID_EMPLOYEE INT REFERENCES EMPLOYES (ID),
	ID_CLIENT INT REFERENCES CLIENTS (ID),
	ID_FREE_DATETIME INT REFERENCES FREE_DATETIME (ID)
);
*/
SELECT * FROM EMPLOYES;
SELECT * FROM SPECIALITY;
